pull_request_rules:
  - name: Automatic approve for Dependabot
    conditions:
      - author=dependabot[bot]
      - "check-success=CodeQL"
      - "check-success=Go Test"
      - "check-success=License Compliance"
    actions:
      review:
        message: auto approve dependabot

  - name: Automatic approve for owner
    conditions:
      - author=gonzolino
      - "check-success=CodeQL"
      - "check-success=Go Test"
      - "check-success=License Compliance"
    actions:
      review:
        message: auto approve owner
