name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.29
        with:
          release-type: simple
          package-name: tado-window-control
