name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          release-type: simple
          package-name: tado-window-control
