name: Release

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          package-name: tado-window-control
          command: release-pr
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          release-type: go
          package-name: tado-window-control
          command: github-release
