name: Review

on:
  push:
    branches:
      - main
  schedule:
    - cron: "32 4 * * 5"

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - run: go test -coverprofile=cover.out -v ./...
      - uses: deepsourcelabs/test-coverage-action@v1.0.3
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2
