name: Review

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened
    branches:
      - main
  schedule:
    - cron: "32 4 * * 5"

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
